databases:
  - name: exhibit_builder
    databaseName: exhibit_builder
    user: exhibit_builder
    plan: free

services:
  - type: web
    name: exhibit_builder
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exhibit_builder
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false